[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11"
kdam = "0.6.1"
rayon = "1.10" 

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "benchmark_day4"
harness = false
